//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wTryNetFree.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n\t\"url\": \"http://185.37.150.104:{{port}}/netfree\",\r\n\t\"username\": \"{{user}}\",\r\n\t" +
            "\"password\": \"{{pass}}\",\r\n\t\"listen\": 1080,\r\n\t\"firefox\": \"..\\\\..\\\\ff_win32\\\\firefo" +
            "x.exe\",\r\n\t\"firefoxprofile\": \"..\\\\..\\\\ff_profile\"\r\n}")]
        public string sjson {
            get {
                return ((string)(this["sjson"]));
            }
        }
    }
}
